name: Sync to Azure Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'Tim Barkman'
        git config --global user.email 'gickis1993@live.com'

    - name: Debug Environment Variables
      run: |
        echo "AZURE_PAT is set to: $AZURE_PAT"

    - name: Push to Azure Repo
      env: 
        AZURE_PAT: ${{ secrets.AZURE_PAT }}
      run: |
        echo "Adding remote with AZURE_PAT: $AZURE_PAT"
        git remote add azure https://dev.azure.com/Capgemini-Sandbox-FS-BE/_git/Tim-Barkman
        git push https://gickis1993:${AZURE_PAT}@dev.azure.com/Capgemini-Sandbox-FS-BE/_git/Tim-Barkman master --force